### ISSUE TITLE
BinTreeNodeReader->readListSize: Invalid token 120

### ISSUE THREAD

**Issue by david-perez** [mgp25/Chat-API#1575] opened 2016-01-27 17:11 UTC
Two days ago I received nodes with token 120, which is untreated in [readListSize()](https://github.com/mgp25/Chat-API/blob/master/src/BinTreeNodeReader.php#L347). As a result an exception occurs. I receive this token periodically.

Running latest version of Chat-API.

```
An exception occurred!
BinTreeNodeReader->readListSize: Invalid token 120
#0 /home/ubuntu/skullberry_tracker/vendor/whatsapp/chat-api/src/BinTreeNodeReader.php(265): BinTreeNodeReader->readListSize(120)
#1 /home/ubuntu/skullberry_tracker/vendor/whatsapp/chat-api/src/BinTreeNodeReader.php(43): BinTreeNodeReader->nextTreeInternal()
#2 /home/ubuntu/skullberry_tracker/vendor/whatsapp/chat-api/src/whatsprot.class.php(2046): BinTreeNodeReader->nextTree('\xC0\x01\xC8I6\xF0\x027\f\xCE\xA4*\x10\x94B...')
#3 /home/ubuntu/skullberry_tracker/vendor/whatsapp/chat-api/src/whatsprot.class.php(303): WhatsProt->processInboundData('\xC0\x01\xC8I6\xF0\x027\f\xCE\xA4*\x10\x94B...')
#4 /home/ubuntu/skullberry_tracker/Tracker.php(312): WhatsProt->pollMessage()
#5 /home/ubuntu/skullberry_tracker/main.php(40): Tracker->run()
#6 {main}
```

```php
while (true) {
            $loop_start = microtime(true);

            /**
             * 0) RESET SOCKET
             */
            if ($loopCount % $this->config->RESET_SOCKET === 0) {
                $reset_tick_start = microtime(true);
                $this->shutdown();
                $this->init();
                $reset_tick_end = microtime(true);
                $reset_took = number_format($reset_tick_end - $reset_tick_start, 4);
                $msg = "Reset socket (reset took $reset_took)";
                $this->logger->log($msg, 'magenta', true, 'reset', $resetCount);
                $resetCount++;
            }

            /**
             * 1) REGULAR SOCKET READ
             */
            $socket_reads = 0;
            $tick_start = microtime(true);
            while ($this->w->pollMessage() === true) { $socket_reads++; }
            $tick_end = microtime(true);
            $socket_reads_took = number_format($tick_end - $tick_start, 4);

            /**
             * 2) WHATSAPP PING
             * Keep connection alive.
             */
            if ($loopCount % $this->config->KEEP_ALIVE === 0) {
                $this->w->sendPing();
                $this->logger->log("Ping sent", 'magenta', true, 'keep-alive', $pingCount);
                $pingCount++;
            }

            $loop_end = microtime(true);
            $loop_took = number_format($loop_end - $loop_start, 4);

            $sleeping = 0;
            if ($loop_took < 2.0) {
                $sleeping = 2.0 - $loop_took;
                usleep($sleeping * 1000000);
            }
            $sleeping = number_format($sleeping, 4);

            echo "... loop took $loop_took, slept $sleeping\n";

            $loopCount++;
        }
```

**Comment by tim-hanssen** [comment] 2016-02-01 08:19
I got the same issue here.

**Comment by rflsouza** [comment] 2016-02-01 13:58
The same error started happening to me today. Call by differents functions (sendSync, and MessageHandler->processEncr).

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'BinTreeNodeReader->readListSize: Invalid token 120' 
in /src/BinTreeNodeReader.php:360
Stack trace:
#0 /src/BinTreeNodeReader.php(284): BinTreeNodeReader->readListSize(120)
#1 /src/BinTreeNodeReader.php(43): BinTreeNodeReader->nextTreeInternal()
#2 /src/whatsprot.class.php(2063): BinTreeNodeReader->nextTree('\xC0\x02\x97\xD2\xF9k\x86\xBC\xB0\xDC\xD4z\xA9gt...')
#3 /src/whatsprot.class.php(311): WhatsProt->processInboundData('\xC0\x02\x97\xD2\xF9k\x86\xBC\xB0\xDC\xD4z\xA9gt...')
#4 /src/whatsprot.class.php(1784): WhatsProt->pollMessage()
#5 /src/whatsprot.class.php(416): WhatsProt->waitForServer('0b')
#6 /src/handlers/MessageHandler.php(333): WhatsProt->sendGetCipherKeysFromUser('XXXXXXXXXXXXX')
6#7 /src/handlers/MessageHandler.php(256): MessageHandler->processEncr in /src/BinTreeNodeReader.php on line 360
```

and 

```
errorType:
PHP Fatal error:  Uncaught exception 'Exception' with message 'BinTreeNodeReader->readListSize: Invalid token 120' 
in /src/BinTreeNodeReader.php:360
Stack trace:
#0 /src/BinTreeNodeReader.php(284): BinTreeNodeReader->readListSize(120)
#1 /src/BinTreeNodeReader.php(43): BinTreeNodeReader->nextTreeInternal()
#2 /src/whatsprot.class.php(2063): BinTreeNodeReader->nextTree('\xC0\x01\xC8^KF\x08\x8D\xA6\xA0\x94\xF9\xD2@0...')
#3 /src/whatsprot.class.php(311): WhatsProt->processInboundData('\xC0\x01\xC8^KF\x08\x8D\xA6\xA0\x94\xF9\xD2@0...')
#4 /src/whatsprot.class.php(1784): WhatsProt->pollMessage()
#5 /src/whatsprot.class.php(1961): WhatsProt->waitForServer('08')
#6 /xgen/whatsApp-5511991254905.php(61): WhatsProt->sendSync(Array)
#7 {main}
  thrown in /src/BinTreeNodeReader.php on line 360

```

**Comment by cooler-farmer** [comment] 2016-02-01 14:01
Same problem - Unable to sync contacts!  #1583

**Comment by AloneMate** [comment] 2016-02-01 17:21
It happens when you try with the same IP. Try to change the IP and then check it. It will work for sure. I also faced same issue and then I changed the IP and it worked.

**Comment by wragnar** [comment] 2016-02-01 17:58
Changed the IP didnt resolve the problem for me. still having 

> PHP Fatal error:  Uncaught exception 'Exception' with message 'BinTreeNodeReader->readListSize: Invalid token 120' in /umeak/script/Chat-API-master/src/BinTreeNodeReader.php:360

**Comment by cooler-farmer** [comment] 2016-02-01 19:25
@AloneMate still not working. Tried different hoster with different ip!

**Comment by viajesclick** [comment] 2016-02-01 23:05
I have the same problem as ip change and still not working

**Comment by Worldexe** [comment] 2016-02-02 11:58
I confirm this happens when `sendSync()` is called with a lot of numbers to sync (>3, at least). Shorter queries got their responses parsed OK.
I tried to decode packet taking 1 or 2 bytes in `getListSize()`, but it does not make sense.
It seems something should be changed in `nextTreeInternal()` before taking any list sizes.

**Comment by mgp25** [comment] 2016-02-02 12:30
@Worldexe false, i tried that and works perfectly

**Comment by bhejosms** [comment] 2016-02-02 13:13
@mgp25 

Can you please let me know what needs to be changed in code and where because I facing same issue for sync.

**Comment by Worldexe** [comment] 2016-02-03 07:53
Maybe, it means stream is compressed? I tried to apply various decompression methods, but it did not work.
Maybe, we can peek into app' DLLs, for example WP? I personally do not have unlocked WP to check that sources myself...

**Comment by wragnar** [comment] 2016-02-04 09:35
I have solve the problem for me.

The issue is related to trying to sync with option 1 a list of contacts that have a modified or deleted whatsapp number.

This in my case was caused because i store all the numbers that send me a message in a db named contacts and when i restart the script try to sync all of then, but the event related to changed numbers and deleted number only aplies to unsuscribe options, so when i restart the script i try to sync whatsappp deleted numbers.

Try to remove all the contact and leave only the ones that you now that exists.

To resolve the issue, you have to look in your events for unsubscribeing the contacts and removing from the contact database.

**Comment by david-perez** [comment] 2016-02-04 10:59
@wragnar I experience the issue when subscribed only to numbers that have WhatsApp.

**Comment by rflsouza** [comment] 2016-02-05 16:39
I got the latest version and continues with the problem in sync. 

I start the program and send synchronize my contacts, all contacts exist and have WhatsApp enabled. 

To help following events:

```
Start - 2016/02/05 14:08:28
[] Logging in as 'BLABLA' (xx11XXXXXxxxx)
connectLogin::start status:
onConnect::Phone number xx11XXXXXxxxx connected successfully!
tx  <stream:features></stream:features>

tx  <auth user="xx11XXXXXxxxx" mechanism="WAUTH-2">42c0xx53038</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>5985xxxxxxxb6240f</challenge>

tx  <response>adfca9xxxxxxx6183fd</response>

rx  <success t="1454688519" props="4" kind="free" statuxx11XXXXXxxxxs="active" creation="1447358878" expiration="4444444444">a4x26fx6</success>

tx  <presence name="BLABLA" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

connectLogin::Connected to WA!!!


Connected to WA

tx  <iq id="03" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="04" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="05" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="06" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

tx  <iq id="07" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>

tx  <iq id="08" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="sync_sid_full_bb4axxx45d7-9e12-1xx5969b8393" index="0" last="true">
tx      <user>+xx11XXXX860x9</user>
tx      <user>+xx11XXXX96x26</user>
tx      <user>+xx11XXXX110x7</user>
tx      <user>+xx11XXXX00160</user>
tx      <user>+xx71XXXX4348</user>
tx      <user>+xx81XXXX140</user>
tx      <user>+xx91XXXXXXX9</user>
tx    </sync>
tx  </iq>

rx  <receipt from="xx3x00@s.whatsapp.net" type="read" id="316f3970xdf77b4208" offline="0" t="1454688496"></receipt>

tx  <ack to="xx3188242600@s.whatsapp.net" class="receipt" id="316f3970exf77b4208" type="read"></ack>

rx  <receipt from="xxx14348@s.whatsapp.net" type="read" id="316f3970xbdf77b4207" offline="0" t="1454688506"></receipt>

tx  <ack to="xx7x14348@s.whatsapp.net" class="receipt" id="316f3970ex7b4207" type="read"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="2"></offline>
rx  </ib>

rx  <presence from="xx11XXXXXxxxx@s.whatsapp.net"></presence>

rx  <presence from="xx3x83@s.whatsapp.net" type="unavailable" last="1454688275"></presence>

onPresenceUnavailable::mynumber: xx11XXXXXxxxx from: xx3x83@s.whatsapp.net is now offline >
rx  <presence from="xx31x039@s.whatsapp.net"></presence>

onPresenceAvailable::mynumber: xx11XXXXXxxxx from: xx3x30039@s.whatsapp.net is now online
rx  <presence from="xxx909@s.whatsapp.net" type="unavailable" last="1454686738"></presence>

... ... .. .. 

onPresenceUnavailable::mynumber: xx11XXXXXxxxx from: xx319x915@s.whatsapp.net is now offline >
rx  <presence from="xx3x21409@s.whatsapp.net" type="unavailable" last="1454684936"></presence>

onPresenceUnavailable::mynumber: xx11XXXXXxxxx from: xxx21409@s.whatsapp.net is now offline >
rx  <presence from="xx7x4348@s.whatsapp.net"></presence>

onPresenceAvailable::mynumber: xx11XXXXXxxxx from: xx71x348@s.whatsapp.net is now online
rx  <presence from="xx3x824@s.whatsapp.net"></presence>

onPresenceAvailable::mynumber: xx11XXXXXxxxx from: xx3x24@s.whatsapp.net is now online
rx  <iq from="s.whatsapp.net" type="result" id="05">
rx    <props version="4">
rx      <prop name="allow" value="all"></prop>
rx      <prop name="archive" value="1"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="call" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="e2e_audio" value="0"></prop>
rx      <prop name="e2e_blists" value="0"></prop>
rx      <prop name="e2e_groups" value="1"></prop>
rx      <prop name="e2e_images" value="1"></prop>
rx      <prop name="e2e_video" value="0"></prop>
rx      <prop name="file_max_size" value="100"></prop>
rx      <prop name="force_long_connect" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="image_max_edge" value="1600"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx      <prop name="max_participants" value="257"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="media_max_autodownload" value="32"></prop>
rx      <prop name="mspes" value="1"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="plaintext_disabled" value="1"></prop>
rx      <prop name="plaintext_reenable_threshold" value="5"></prop>
rx      <prop name="qr" value="1"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="small_call_btn" value="1"></prop>
rx      <prop name="source" value="2"></prop>
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="upload_oom_hprof_enabled" value="1"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="wbarchive" value="1"></prop>
rx    </props>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="02">
rx    <config platform="gcm" id="wlsok_9eZ5CxZmv3He1"></config>
rx  </iq>

rx  <iq from="xx11XXXXXxxxx@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

onGetError::mynumber: xx11XXXXXxxxx 
from: xx11XXXXXxxxx@s.whatsapp.net 
data: Array
(
    [tag] => error
    [attributeHash] => Array
        (
            [code] => 404
            [text] => item-not-found
        )

    [children] => 
    [data] => 
)
 
errorType: 
rx  <iq from="xx11XXXXXxxxx@s.whatsapp.net" type="error" id="03">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

onGetError::mynumber: xx11XXXXXxxxx 
from: xx11XXXXXxxxx@s.whatsapp.net 
data: Array
(
    [tag] => error
    [attributeHash] => Array
        (
            [code] => 404
            [text] => item-not-found
        )

    [children] => 
    [data] => 
)
 
errorType: privacy
rx  <iq from="g.us" type="result" id="06">
rx    <groups>
rx      <group id="xx11x95-1450092973" creator="xx1x5@s.whatsapp.net" creation="1450092973" subject="BLABLA - Arenilda" s_t="1450092973" s_o="xx1x95@s.whatsapp.net">
rx        <participant jid="xx11XXXXXxxxx@s.whatsapp.net" type="admin"></participant>
rx      </group>
rx    </groups>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="07">
rx    <lists></lists>
rx  </iq>

rx  <presence from="xx1199x0160@s.whatsapp.net" type="unavailable" last="1454688252"></presence>

onPresenceUnavailable::mynumber: xx11XXXXXxxxx from: xx11x0160@s.whatsapp.net is now offline >
rx  <iq from="s.whatsapp.net" type="result" id="04">
rx    <config platform="gcm" id="wlsok_9eZ5C:APA9xixTZmv3He1"></config>
rx  </iq>

PHP Fatal error:  Uncaught exception 'Exception' with message 'BinTreeNodeReader->readListSize: 
invalid list size in readListSize: token 120' in src/BinTreeNodeReader.php:358
Stack trace:
#0 src/BinTreeNodeReader.php(284): BinTreeNodeReader->readListSize(120)
#1 src/BinTreeNodeReader.php(43): BinTreeNodeReader->nextTreeInternal()
#2 src/whatsprot.class.php(2082): BinTreeNodeReader->nextTree('\xC0\x01\x8F\x830\xB7\xF1\xDF\xE0N\xE0u\xE8\x00\x96...')
#3 src/whatsprot.class.php(311): WhatsProt->processInboundData('\xC0\x01\x8F\x830\xB7\xF1\xDF\xE0N\xE0u\xE8\x00\x96...')
#4 src/whatsprot.class.php(1803): WhatsProt->pollMessage()
#5 src/whatsprot.class.php(1980): WhatsProt->waitForServer('08')
#6 /whatsApp-xx11XXXXXxxxx.php(61): WhatsProt->sendSync(Array)
#7 {main}
  thrown in src/BinTreeNodeReader.php on line 358

```

**Comment by fsadario** [comment] 2016-02-10 19:09
Got same error with the lastest version. Can't get it work. I just rolled back to a old version and it works OK. Any idea about how get work the last version?

**Comment by hypertech** [comment] 2016-02-14 11:28
I have same issue on sync, @mgp25 any news about solution of this ?

**Comment by mgp25** [comment] 2016-02-14 11:57
@hypertech i dont have enought info to reproduce this error, i guess only people using the API with bad behaviours are getting this.

**Comment by SudoHenk** [comment] 2016-02-16 17:20
@mgp25 It happens to me when I keep logged in for like 4+ hours.

**Comment by hypertech** [comment] 2016-02-16 18:04
@SudoHenk i do not think it depend on this, and it happen randomly, if i simple ignore this error and do request again - it works ok, it is simple some new data from whatsapp servers witch need to handle in code

**Comment by mgp25** [comment] 2016-02-16 21:15
This will be fixed in the next release. Already tracked and solved.

Regards

**Closed** 2016-02-19 19:10 UTC
