### ISSUE TITLE
ntegrity constraint violation: 19 column prekey_id is not unique' in SqliteAxolotlStore.php:280

### ISSUE THREAD

**Issue by Expressit** [mgp25/Chat-API#1754] opened 2016-03-24 14:09 UTC
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] You are using PHP > 5.6
- [x] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [x] You have checked if someone has already asked the same issue you have.
- [x] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [x] Is not a programming question.
- [x] You are using latest Chat API code.

### Error
Post your error below:
[24-Mar-2016 09:25:36 ] PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 column prekey_id is not unique' in /chat_api_20160321/src/SqliteAxolotlStore.php:152 
I get this alot and I don't get my friends messages. I also tried delete the axolot db but it does not make a difference. ps. log is from bottom to top

### Debug log
Post your debug log below:

```xml
2016-03-24_09:03:55:0458 tx      </key>
2016-03-24_09:03:55:0446 tx        <value>302ae26b10b1afec5717e5fc682c1561f9015286e90b8a437751125340591503</value>
2016-03-24_09:03:55:0436 tx        <id>40c3cf</id>
2016-03-24_09:03:55:0423 tx      <key>
2016-03-24_09:03:55:0412 tx      </key>
2016-03-24_09:03:55:0402 tx        <value>35b599277a1e3eb80cf323cab43de3b479c8b9ec9d3747fe649be523a9dbad2c</value>
2016-03-24_09:03:55:0392 tx        <id>40c3ce</id>
2016-03-24_09:03:55:0382 tx      <key>
2016-03-24_09:03:55:0372 tx      </key>
2016-03-24_09:03:55:0342 tx        <value>7248e403c5f66835acc78301c31a4475d0c4c434dd6285e7d95d1b1c0f5fb511</value>
2016-03-24_09:03:55:0332 tx        <id>40c3cd</id>
2016-03-24_09:03:55:0323 tx      <key>
2016-03-24_09:03:55:0313 tx      </key>
2016-03-24_09:03:55:0304 tx        <value>1ffdfdeb30b5574fddacb55f74e83af9f8685785348fa609c6b4da74d29e9760</value>
2016-03-24_09:03:55:0294 tx        <id>40c3cc</id>
2016-03-24_09:03:55:0285 tx      <key>
2016-03-24_09:03:55:0276 tx      </key>
2016-03-24_09:03:55:0265 tx        <value>0896ea30818110eb0021cf365783a93f3e92e680e79f564bbba2a9bff121021c</value>
2016-03-24_09:03:55:0255 tx        <id>40c3cb</id>
2016-03-24_09:03:55:0245 tx      <key>
2016-03-24_09:03:55:0235 tx      </key>
2016-03-24_09:03:55:0225 tx        <value>462650051d2c6445d7a2056132465c51bec7d8c1dd42dbf72694acce494d8421</value>
2016-03-24_09:03:55:0216 tx        <id>40c3ca</id>
2016-03-24_09:03:55:0206 tx      <key>
2016-03-24_09:03:55:0196 tx      </key>
2016-03-24_09:03:55:0187 tx        <value>d33bf3831003d2693fa85944622f595fda0a3ca9c6eadd10d3c48ccdc9555928</value>
2016-03-24_09:03:55:0176 tx        <id>40c3c9</id>
2016-03-24_09:03:55:0167 tx      <key>
2016-03-24_09:03:55:0158 tx      </key>
2016-03-24_09:03:55:0148 tx        <value>952abb266a4befa240dddd5af762c305bb8b3d0d243e4773de5a7b99e9bb037d</value>
2016-03-24_09:03:55:0139 tx        <id>40c3c8</id>
2016-03-24_09:03:55:0128 tx      <key>
2016-03-24_09:03:55:0117 tx      </key>
2016-03-24_09:03:55:0106 tx        <value>4df59be359627b1778395677862030f1dc4518edac332dfa95e38367126bf17d</value>
2016-03-24_09:03:55:0079 tx        <id>40c3c7</id>
2016-03-24_09:03:55:0069 tx      <key>
2016-03-24_09:03:55:0059 tx    <list>
2016-03-24_09:03:55:0050 tx    <type>05</type>
2016-03-24_09:03:55:0041 tx    <registration>212c91d4</registration>
2016-03-24_09:03:55:0034 tx    <identity>bf8a9ea2070557f4c87b3cf3169649a1d562d1dde784c1ac956c1257541e766d</identity>
2016-03-24_09:03:55:0019 -> Decrypted Message: Bad Mac! No valid sessions - /whatsapp_api_20160321/src/libaxolotl-php/SessionCipher.php - 178Message B2443F3CD0BB7766DA could not be decrypted, sending retry. tx  <iq id="0f" to="s.whatsapp.net" type="set" xmlns="encrypt">
2016-03-24_09:03:55:0011 tx  <ack to="TELNUMBER@s.whatsapp.net" class="message" id="B2443F3CD0BB7766DA" t="1458806560"></ack>
2016-03-24_09:03:54:9999 rx  </message>
2016-03-24_09:03:54:9968 rx    <enc v="2" type="msg" count="1">330a2105106829bbecbf4c3387b3248a32639c5231e39e8a6fd98a3208a7537a49561155101d180122a00275a4a847e94e787b64dd7054163a83d93976923b43b67036f7539b2968eea99f445d07d78ee06859d205fabb19b68737d1d8358c035dd6216a9e1812bd964678e5a3552c9c88f50207b3475a9004d3f988b27938065023da1fdd8425a369054d2dba7b8708f44f6360c83d17362d2c98287594dcdbdeccaa2de1e6b8ea5cafef68e220f1aed3993b348f8bd16e250726eb0494c183d3f9fbccf1d89e4bcc27f51ca6a724adfab39b39f5d6d173b70ae1a38142236c0ed0ac6b16f148624ceb41161a129c2f51bd9eb62a0ac4a0e1f4f1fdd866d279d136721a8db252915e58618d34dc1125e4d1e7c984223ebe6b88f8df71835ca9246cab0daf3c836d8a2bfc359959b32753de6ad101e872303b3d2373e05c6d62d5fc67cdad0000e8fa99d461ffe7a69851e8e8</enc>
2016-03-24_09:03:54:9954 rx  <message from="TELNUMBER@s.whatsapp.net" type="text" id="B2443F3CD0BB7766DA" t="1458806560" notify="Name">
2016-03-24_09:02:41:0962 rx  <ack from="TELNUMBER@s.whatsapp.net" class="receipt" type="retry" id="B2443F3CD0BB7766DA"></ack>
2016-03-24_09:02:41:0954 tx  </receipt>
2016-03-24_09:02:41:0946 tx    <registration>188528b5</registration>
2016-03-24_09:02:41:0939 tx    <retry v="1" count="1" id="B2443F3CD0BB7766DA" t="1458806555"></retry>
2016-03-24_09:02:41:0931 tx  <receipt id="B2443F3CD0BB7766DA" to="TELNUMBER@s.whatsapp.net" type="retry" t="1458806555">
2016-03-24_09:02:41:0923 rx  <ack from="TELNUMBER@s.whatsapp.net" class="receipt" type="retry" id="B2443F3CD0BB7766DA"></ack>
2016-03-24_09:02:41:0915 rx  </ib>
2016-03-24_09:02:41:0907 rx    <offline count="0"></offline>
2016-03-24_09:02:41:0899 rx  <ib from="s.whatsapp.net">
2016-03-24_09:02:41:0890 rx  </iq>
2016-03-24_09:02:41:0880 rx    <config platform="gcm" id="qMFuw_813x9:APA91bRjwOayh6VW6lvVoe1N3IUdNhIUMDyWrqW7jk05wXAisi9bZWjES810JZuKva4Kru_j8Jek-fx28pLl2eRAE_FVqzt83nB_hXnywEegw27_C_5NxNLjPeFHnjnWObI09FQfdPym"></config>
2016-03-24_09:02:41:0872 rx  <iq from="s.whatsapp.net" type="result" id="0e">
2016-03-24_09:02:41:0864 rx  </iq>
2016-03-24_09:02:41:0856 rx    <error code="404" text="item-not-found"></error>
2016-03-24_09:02:41:0847 rx  <iq from="lokalnumber@s.whatsapp.net" type="error" id="0d">
2016-03-24_09:02:41:0823 rx  <presence from="lokalnumber@s.whatsapp.net"></presence>
2016-03-24_09:02:41:0815 tx  </receipt>
2016-03-24_09:02:41:0808 tx    <registration>188528b5</registration>
2016-03-24_09:02:41:0800 tx    <retry v="1" count="1" id="B2443F3CD0BB7766DA" t="1458806554"></retry>
2016-03-24_09:02:41:0792 -> Decrypted Message: Bad Mac! No valid sessions - /whatsapp_api_20160321/src/libaxolotl-php/SessionCipher.php - 178Message B2443F3CD0BB7766DA could not be decrypted, sending retry. tx  <receipt id="B2443F3CD0BB7766DA" to="TELNUMBER@s.whatsapp.net" type="retry" t="1458806554">
2016-03-24_09:02:41:0784 tx  <ack to="TELNUMBER@s.whatsapp.net" class="message" id="B2443F3CD0BB7766DA" t="1458806554"></ack>
2016-03-24_09:02:41:0777 rx  </message>
2016-03-24_09:02:41:0770 rx    <enc v="2" type="msg" count="1">330a2105106829bbecbf4c3387b3248a32639c5231e39e8a6fd98a3208a7537a49561155101b180122800189e08838fa436e180ec50666e4a0d912fa9698afe61fd2d197936844e3ecd9a967bb6c5d56b52a43637c19065da3fb39bf24dff15baebb020d80edbf4d9bf1e363a5cb59b0062aac866cc937bbebedbd57a9d0d82d54bf6b149321217b788a0996952e0e51948c5ceaf42d58a080d344e95e9c76238ea5289eec592fe2a2709f9221f04eac225e30</enc>
2016-03-24_09:02:41:0764 rx  <message from="TELNUMBER@s.whatsapp.net" type="text" id="B2443F3CD0BB7766DA" t="1458806554" notify="Name">
2016-03-24_09:02:41:0757 tx  </iq>
2016-03-24_09:02:41:0748 tx    <config></config>
2016-03-24_09:02:41:0740 tx  <iq id="0e" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
2016-03-24_09:02:41:0732 tx  </iq>
2016-03-24_09:02:41:0723 tx    </query>
2016-03-24_09:02:41:0715 tx      <list name="default"></list>
2016-03-24_09:02:41:0707 tx    <query> 
```
And it always ends with :

```xml
[24-Mar-2016 10:17:39] PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 column prekey_id is not unique' in /chat_api_20160321/src/SqliteAxolotlStore.php:152

or 

[24-Mar-2016 12:57:35] PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 19 column prekey_id is not unique' in /chat_api_20160321/src/SqliteAxolotlStore.php:280
[2016-03-24_12:56:35] 6056 rx  <ack from="TELNUMBER@s.whatsapp.net" class="receipt" type="retry" id="D00C022438331AF834"></ack> 
```

**Comment by rflsouza** [comment] 2016-03-24 16:21
I got the same error, I am testing the solution and so are valid, I will update the git.

I find this problema in storePreKey and storeSignedPreKey. Just change de SQL from "_INSERT_" to "_INSERT OR REPLACE_".

Hugs

**Comment by rflsouza** [comment] 2016-03-24 17:34
With the change to replace the problem is resolved. But my application consume many CPU to Decrypted Message. 

In this version it seems that I started to receive many messages "Bad MAC", and he can not make decrypted message, trying several times.

**Comment by gratbrav** [comment] 2016-03-24 23:49
@rflsouza "Bad MAC": you use iOS 9.3? i think its a problem since the last kenynote. sorry, i know its not the topic :)

**Comment by mgp25** [comment] 2016-03-25 18:35
Added and fixed in the next release!

Regards

**Closed by mgp25** 2016-03-25 18:35 UTC

**Comment by Expressit** [comment] 2016-03-25 21:54
### Error
Hi mpg, the fix like proposed above isn't the answer yet, now I get following  error all the time after applying above "INSERT OR UPDATE"
[25-Mar-2016 12:35:41] PHP Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /src/whatsprot.class.php:297

    public function containsSignedPreKey($signedPreKeyId)
    {
**        $sql = 'SELECT `record` FROM signed_prekeys where `prekey_id` = :id';**
        $query = $this->db->prepare($sql);

        $query->execute(
          [
                  ':id' => $signedPreKeyId,
              ]
      );
        $row = $query->fetch(PDO::FETCH_ASSOC);
        if ($row == null || $row === false) {
            return false;
        } 


### Debug log
ps code is again from bottom to top

```xml
2016-03-25_12:22:46:2228 tx    <retry v="1" count="1" id="06A256C32712D322165" t="1458904961"></retry>
2016-03-25_12:22:46:2219 -> Decrypted Message: Bad Mac! Bad Mac! No valid sessions - /src/libaxolotl-php/SessionCipher.php - 178Message 06A256C32712D322165 could not be decrypted, sending retry. tx  <receipt id="06A256C32712D322165" to="ERRORTELNUMBER@s.whatsapp.net" type="retry" t="1458904961">
2016-03-25_12:22:46:2207 tx  <ack to="ERRORTELNUMBER@s.whatsapp.net" class="message" id="06A256C32712D322165" t="1458904961"></ack>
2016-03-25_12:22:46:2195 rx  </iq>
2016-03-25_12:22:46:2183 rx    </list>
2016-03-25_12:22:46:2171 rx      </user>
2016-03-25_12:22:46:2160 rx        </key>
2016-03-25_12:22:46:2148 rx          <value>a06bfcc8354ec21d52133035051231d6fffbeaca5c7ef33ca59f5c35a374a808</value>
2016-03-25_12:22:46:2134 rx          <id>000071</id>
2016-03-25_12:22:46:2122 rx        <key>
2016-03-25_12:22:46:2110 rx        </skey>
2016-03-25_12:22:46:2102 rx          <signature>0a591d18c8570840a3889b1b425310a2ad09a30eb93067b9d4667804eda168809bd5a5a61aab7b52b5123b1d0c0ebbf94d1d2fb49b3d4c4f03189a948a0dc78a</signature>
2016-03-25_12:22:46:2093 rx          <value>191d0fbe56d85518bb5d5fee7a9a453125ccfc6db9cb44c53c837573fc16873d</value>
2016-03-25_12:22:46:2084 rx          <id>000005</id>
2016-03-25_12:22:46:2073 rx        <skey>
2016-03-25_12:22:46:2060 rx        <identity>22fe5b7b1ec5fc67a46d5b5b0b4b7ab996958ba569bdc75402a26d5c364f890c</identity>
2016-03-25_12:22:46:1996 rx        <type>05</type>
2016-03-25_12:22:46:1984 rx        <registration>00000320</registration>
2016-03-25_12:22:46:1972 rx      <user jid="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:46:1961 rx    <list>
2016-03-25_12:22:46:1949 rx  <iq from="s.whatsapp.net" type="result" id="36">
2016-03-25_12:22:46:1937 tx  </iq>
2016-03-25_12:22:46:1928 tx    </key>
2016-03-25_12:22:46:1918 tx      <user jid="ERRORTELNUMBER@s.whatsapp.net"></user>
2016-03-25_12:22:46:1909 tx    <key>
2016-03-25_12:22:46:1899 tx  <iq id="36" xmlns="encrypt" type="get" to="s.whatsapp.net">
2016-03-25_12:22:46:1889 tx  <ack to="ERRORTELNUMBER@s.whatsapp.net" class="message" id="06A256C32712D322165" t="1458904961"></ack>
2016-03-25_12:22:46:1880 rx  </message>
2016-03-25_12:22:46:1793 rx    <enc v="2" type="pkmsg">3308b28c9a05122105abd0061e51d1a1e18dbf60f9c5d159a86d8ad5fd295670805dd8e10fb871f1081a210522fe5b7b1ec5fc67a46d5b5b0b4b7ab996958ba569bdc75402a26d5c364f890c228304330a21051ec025c5e587a64d81addf59cc71050205e15401668dfd3b41df00784383aa761000180022d00314b0bcd3e4daded7a29f264e6e11b68edea506e14a7a8f48134eaa28e3a22722068869a48b557aa37c26aea3ae3bf7a76ecfc247ad14b5e5e72f10fee1d3c4cff2dda22bbe0af3962c1be93e00e43eed913d174d0023d92b356e8f5720b795b31666df6603aa954f7291824e65ada2f932b9edfa36754cdd927c20d9fb2885d79602609016b13be8d8d1e879b0aa8807a96e713d4de3cbb360b424be29264372881fe76543375d3a2d00f8198ed7944ccf34b777add575b6a61775dbab12963c9c55ee1833f961e2193590690b744d4e7c0cabded7465623bfe5c76e68ce6b11bfe5d5f6701b57c426c8ed4df702a1b96d46dab7a8de44e01941dc27984ae6d61b14ac8e5415654e15531b6dfd5991f1fca65773ee7305c3c88b15b654548711b47095d6b30f1082618caf8e5d111b3f12d5e7a9509236acd939af764c99a6dd88947ac10f6378a5c8326a62bd9688a3529d282cb648259c33e1561635917a9008e39f4fea592618bfe93d6af82b5008061852392d6de596b967e212ceeb54ad355dc642202ea2f58c235327d1ae12be44882e0af3f1a8dcbd761fb19d6b5a0f682a2356650ced1b9851c7fb341ecb5429c17da0780a7babf8332d95aa8389d11f01fccb431cb0b6b486756514d2bb6844d6b832fea1015428a00630b40a</enc>
2016-03-25_12:22:46:1783 rx  <message from="ERRORTELNUMBER@s.whatsapp.net" type="text" id="06A256C32712D322165" t="1458904961" notify="G.D.">
2016-03-25_12:22:34:2342 rx  </chatstate>
2016-03-25_12:22:34:2314 rx    <paused></paused>
2016-03-25_12:22:34:2307 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:28:9477 rx  </chatstate>
2016-03-25_12:22:28:9447 rx    <composing></composing>
2016-03-25_12:22:28:9436 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:28:7004 rx  </chatstate>
2016-03-25_12:22:28:6975 rx    <paused></paused>
2016-03-25_12:22:28:6969 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:16:5186 rx  </chatstate>
2016-03-25_12:22:16:5153 rx    <composing></composing>
2016-03-25_12:22:16:5139 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:06:4941 rx  </chatstate>
2016-03-25_12:22:06:4914 rx    <composing></composing>
2016-03-25_12:22:06:4907 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:05:0914 rx  </chatstate>
2016-03-25_12:22:05:0881 rx    <paused></paused>
2016-03-25_12:22:05:0870 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:22:01:1127 rx  <iq from="s.whatsapp.net" type="result" id="35" t="1458904921"></iq>
2016-03-25_12:22:01:1116 tx  </iq>
2016-03-25_12:22:01:1103 tx    <ping></ping>
2016-03-25_12:22:01:1093 tx  <iq id="35" xmlns="w:p" type="get" to="s.whatsapp.net">
2016-03-25_12:21:56:7797 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="1458904916"></presence>
2016-03-25_12:21:55:3784 rx  </chatstate>
2016-03-25_12:21:55:3758 rx    <composing></composing>
2016-03-25_12:21:55:3750 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:47:4530 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="deny"></presence>
2016-03-25_12:21:45:2509 rx  </chatstate>
2016-03-25_12:21:45:2480 rx    <composing></composing>
2016-03-25_12:21:45:2467 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:40:9303 rx  <presence from="TELNUMBER@s.whatsapp.net"></presence>
2016-03-25_12:21:22:1877 rx  </chatstate>
2016-03-25_12:21:22:1864 rx    <paused></paused>
2016-03-25_12:21:22:1854 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:18:2282 rx  </chatstate>
2016-03-25_12:21:18:2252 rx    <composing></composing>
2016-03-25_12:21:18:2245 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:17:5463 rx  </chatstate>
2016-03-25_12:21:17:5435 rx    <paused></paused>
2016-03-25_12:21:17:5391 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:13:1703 rx  </chatstate>
2016-03-25_12:21:13:1624 rx    <composing></composing>
2016-03-25_12:21:13:1493 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:21:07:7877 rx  <presence from="ERRORTELNUMBER@s.whatsapp.net"></presence>
2016-03-25_12:21:01:4832 rx  <iq from="s.whatsapp.net" type="result" id="34" t="1458904861"></iq>
2016-03-25_12:21:01:4820 tx  </iq>
2016-03-25_12:18:00:3963 tx    <ping></ping>
2016-03-25_12:18:00:3955 tx  <iq id="31" xmlns="w:p" type="get" to="s.whatsapp.net">
2016-03-25_12:17:41:8136 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="deny"></presence>
2016-03-25_12:17:33:2148 rx  <presence from="ERRORTELNUMBER@s.whatsapp.net" type="unavailable" last="1458904653"></presence>
2016-03-25_12:17:01:8607 rx  <iq from="s.whatsapp.net" type="result" id="30" t="1458904621"></iq>
2016-03-25_12:17:01:8599 tx  </iq>
2016-03-25_12:17:01:8589 tx    <ping></ping>
2016-03-25_12:17:01:8582 tx  <iq id="30" xmlns="w:p" type="get" to="s.whatsapp.net">
2016-03-25_12:16:59:7735 rx  <presence from="ERRORTELNUMBER@s.whatsapp.net" type="unavailable" last="1458904619"></presence>
2016-03-25_12:16:51:2887 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="1458904611"></presence>
2016-03-25_12:16:36:9780 rx  </chatstate>
2016-03-25_12:16:36:9757 rx    <paused></paused>
2016-03-25_12:16:36:9747 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:16:28:2705 rx  </chatstate>
2016-03-25_12:16:28:2679 rx    <composing></composing>
2016-03-25_12:16:28:2670 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:16:27:5230 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="deny"></presence>
2016-03-25_12:16:17:5816 rx  </chatstate>
2016-03-25_12:16:17:5789 rx    <composing></composing>
2016-03-25_12:16:17:5783 rx  <chatstate from="ERRORTELNUMBER@s.whatsapp.net">
2016-03-25_12:16:11:6502 rx  <presence from="TELNUMBER@s.whatsapp.net" type="unavailable" last="deny"></presence>
2016-03-25_12:16:04:1669 rx  <presence from="ERRORTELNUMBER@s.whatsapp.net"></presence> 
```
