### ISSUE TITLE
Getting blocked

### ISSUE THREAD

**Issue by markusschweitzer** [mgp25/Chat-API#2111] opened 2016-08-02 17:57 UTC
Make sure these boxes are checked before submitting your issue -- thank you!

- [X] You are using PHP > 5.6
- [X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [X] You have checked if someone has already asked the same issue you have.
- [X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [X] Is not a programming question.
- [X] You are using latest Chat API code.

Hi, first let me say thanks for that awesome work you have done here. I really appreciate it.
I'm trying really hard to get my "bot" (question answer stuff) working - but I'm getting banned everytime I try. Can you maybe point out, where the issue in my code is?

I have read the wiki regarding sending messages and login procedures, but i think im doing it right :/

Maybe I need to kind of sync the contacts from the messages I am receiving?

### Code:
```php
<?php

require_once __DIR__.'/../src/whatsprot.class.php';
require_once __DIR__.'/../src//events/MyEvents.php';


$username = '*number*';
$password = '*pw*';
$nickname = '*nicknam*';
$debug = false;

$client = new SoapClient("Service.asmx?wsdl");

function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{
    echo "Message from $name:$body\n";
    try {
        global $w;
        global $client;
        $params = array(
          "from" => $from,
          "id" => $id,
          "input" => $body
        );
        $w->sendMessageComposing($from);
        $answer =  $client->GetAnswer($params)->GetAnswerResult;
	$w->sendMessagePaused($from);
		if(!empty($answer)){
				  $w->sendMessage($from, $answer);
                }
      }
      catch (Exception $e)
      {
        echo 'Exception: ',  $e->getMessage(), "\n";
        $w->sendMessagePaused($from);
        $w->sendMessage($from, "some error message");
      }
}

echo "[] Logging in as '$nickname' ($username)\n";
$w = new WhatsProt($username, $nickname, $debug);
$w->eventManager()->bind("onGetMessage", "onGetMessage");

$w->connect();

$w->loginWithPassword($password);

echo "[*] Connected to WhatsApp\n\n";

while (1){
  $w->pollMessage();
}

```

**Comment by MoudiZd** [comment] 2016-08-03 06:51
now @0xTryCatch will close this and add a flag to it as duplicate.

Don't open like these issues,and in some words i say.

Now whatsapp become smarter than blocking just a code used,or protocol of communication it is now going to block on activities.

I ran 3 days with a normal behavior and i do chat with all my friend and don't use any type of automation but the result is a block , because whatsapp can detect your ip your phone origin number ,...... and can monitor the contact you talk with , so it can know if the number of contacts you contact with them daily is huge so you are not a really human,and whatsapp can know if all contacts you talk with them is not from your country also it will know you are not a human,etc ........

Working with Whatsapp become a bit tidy because whatsapp now is going to close all the way around the client, even a whatsapp official version client can be blocked if it work in an unexpected behavior that whatsapp want

So by conclusion this Api do well but have some bugs but the big problem is in the side of whatsapp activity monitoring is doing all efforts to prevent anyone to use its service in a strange way


Regards !

**Comment by tarun72888** [comment] 2016-08-03 10:41
i think new version have many updates internally, but we do change only token and no. of new version only in he api... this is not enough.. because in old version 2.12.440. we not face problem this like.. something need to update..

**Closed** 2016-08-03 11:06 UTC
